import type { LucideIcon } from "lucide-react";
import {
  Bell,
  BookOpen,
  Brain,
  CheckCircle2,
  ClipboardList,
  Cloud,
  Code2,
  Database,
  FileCode2,
  Gauge,
  GitBranch,
  Globe2,
  Hexagon,
  Layout,
  Link2,
  Lock,
  RefreshCw,
  Server,
  TableProperties,
  TestTube2,
  Users,
  Workflow,
} from "lucide-react";
import type { SimpleIcon } from "simple-icons";
import {
  siAntdesign,
  siBootstrap,
  siCss,
  siDocker,
  siEjs,
  siEthereum,
  siExpress,
  siGithubactions,
  siGraphql,
  siHtml5,
  siJavascript,
  siJest,
  siMongodb,
  siMysql,
  siNextdotjs,
  siNodedotjs,
  siPayloadcms,
  siPostgresql,
  siPython,
  siReact,
  siRedux,
  siRemix,
  siRust,
  siSentry,
  siSocketdotio,
  siTailwindcss,
  siTypescript,
} from "simple-icons";

type BrandDef = { kind: "brand"; icon: SimpleIcon };
type LineDef = { kind: "line"; icon: LucideIcon };
export type IconDef = BrandDef | LineDef;

const brand = (icon: SimpleIcon): BrandDef => ({ kind: "brand", icon });
const line = (icon: LucideIcon): LineDef => ({ kind: "line", icon });

/** Explicit registry of only the icons used by expertise cards. */
export const skillIconRegistry: Record<string, IconDef> = {
  react: brand(siReact),
  nextjs: brand(siNextdotjs),
  remix: brand(siRemix),
  redux: brand(siRedux),
  typescript: brand(siTypescript),
  javascript: brand(siJavascript),
  html5: brand(siHtml5),
  css3: brand(siCss),
  tailwind: brand(siTailwindcss),
  antd: brand(siAntdesign),
  bootstrap: brand(siBootstrap),
  ejs: brand(siEjs),
  nodejs: brand(siNodedotjs),
  express: brand(siExpress),
  graphql: brand(siGraphql),
  socketio: brand(siSocketdotio),
  payload: brand(siPayloadcms),
  postgresql: brand(siPostgresql),
  mysql: brand(siMysql),
  mongodb: brand(siMongodb),
  docker: brand(siDocker),
  githubactions: brand(siGithubactions),
  sentry: brand(siSentry),
  jest: brand(siJest),
  python: brand(siPython),
  rust: brand(siRust),
  ethereum: brand(siEthereum),
  // Intentional generics where brand marks are unavailable or unsuitable
  aws: line(Cloud),
  azure: line(Cloud),
  api: line(Link2),
  lock: line(Lock),
  check: line(CheckCircle2),
  refresh: line(RefreshCw),
  sql: line(Database),
  schema: line(TableProperties),
  index: line(Hexagon),
  gauge: line(Gauge),
  pipeline: line(Workflow),
  test: line(TestTube2),
  bell: line(Bell),
  review: line(Code2),
  plan: line(ClipboardList),
  clipboard: line(ClipboardList),
  cycle: line(RefreshCw),
  globe: line(Globe2),
  mentor: line(Users),
  blockchain: line(Hexagon),
  brain: line(Brain),
  layout: line(Layout),
  server: line(Server),
  database: line(Database),
  cloud: line(Cloud),
  users: line(Users),
  learn: line(BookOpen),
  ejsFallback: line(FileCode2),
  git: line(GitBranch),
};

export function resolveSkillIcon(key: string): IconDef {
  return skillIconRegistry[key] ?? line(Code2);
}
